## What are NumPy Arrays ?

NumPy is a Python package that stands for ‘Numerical Python’.It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++ etc.It is also useful in linear algebra, random number capability etc. NumPy array can also be used as an efficient multi-dimensional container for generic data.

**NumPy Array:** Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements.

![](NumPy-array.png)

In [1]:
# Import NumPy library
import numpy as np

## Single & Multi-dimensional Numpy Array:

In [2]:
# Single dimensional array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Multi-dimensional array
b = np.array([(1,2,3),(4,5,6)])    # np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# Data type of array object
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## NumPy Array v/s List

We use python NumPy array instead of a list because of the below three reasons:

1. Less Memory
2. Fast
3. Convenient

The very first reason to choose python NumPy array is that it occupies less memory as compared to list. Then, it is pretty fast in terms of execution and at the same time, it is very convenient to work with NumPy. So these are the major advantages that Python NumPy array has over list.

## Python NumPy Operation

**1. ndim :** You can find the dimension of the array, whether it is a two-dimensional array or a single dimensional array.

In [5]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(c.ndim)     #Since the output is 2, it is a two-dimensional array (multi dimension)

2


**2. itemsize :** You can calculate the byte size of each element.

In [6]:
d = np.array([4,6,7])
print(d.itemsize)   #So every element occupies 4 byte in the above numpy array.

4


**3. dtype :** You can find the data type of the elements that are stored in an array. So, if you want to know the data type of a particular element, you can use ‘dtype’ function which will print the datatype along with the size.

In [7]:
x = np.array([1.7,7.6,3.1,9.5])
print(x.dtype)

float64


In [8]:
#Calculating size and shape of an array
x = np.array([(9,3,6),(3,5,6)])
print(x.size)
print(x.shape)

6
(2, 3)


**4. reshape :** Reshape is when you change the number of rows and columns which gives a new view to an object. 

In [9]:
a = np.array([(8,9,10),(11,12,13)])
print(a)
b = a.reshape(3,2)
print('-'*20)
print(b)

[[ 8  9 10]
 [11 12 13]]
--------------------
[[ 8  9]
 [10 11]
 [12 13]]


**5. Slicing :** Slicing is basically extracting particular set of elements from an array. This slicing operation is pretty much similar to the one which is there in the list as well.

In [10]:
# We have an array and we need a particular element (say 3) out of a given array.
x = np.array([(2,5,7,6),(7,6,3,6)])
print(x[1,2])
#Here, the array(2,5,7,6) is your index 0 and (7,6,3,6) is index 1 of the python numpy array. 
#Therefore, we have printed the second element from the 1th index.

3


In [11]:
#let’s say we need the 2nd element from the all index of the array
x = np.array([(2,3,4,2),(5,6,7,2),(8,9,10,2)])
print(x[0:,2])
# Here colon represents all the rows, including zero. 
# Now to get the 2nd element, we’ll call index 2 from all of the rows which gives us the value 4,7 and 10 .

[ 4  7 10]


In [12]:
x = np.array([(8,9),(10,11),(12,13)])
print(x[0:2,1])
#As you can see in the above code, only 9 and 11 gets printed. Now when I have written 0:2, this does not include the second index of the third row of an array. 
#Therefore, only 9 and 11 gets printed else you will get all the elements i.e [9 11 13].

[ 9 11]


**6. linspace :** This is another operation in python numpy which returns evenly spaced numbers over a specified interval.

In [13]:
# it will print 10 values between 1 to 3.
x = np.linspace(1,3,10)
print(x)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


**7. min/ max/ sum :**

In [14]:
x = np.array([(2,4,6),(5,7,2),(8,4,3)])
print(x.min())
print(x.max())
print(x.sum())

2
8
41


In [15]:
# Sum along the axis of an array
print(x.sum(axis = 0))
print('-'*15)
print(x.sum(axis = 1))

[15 15 11]
---------------
[12 14 15]


**8. Square root & Standard Deviation**

In [16]:
x = np.array([(6,4,6),(3,5,8),(9,6,4)])
print(np.sqrt(x))   # square root
print('-'*15)
print(np.std(x))   # standard deviation

[[2.44948974 2.         2.44948974]
 [1.73205081 2.23606798 2.82842712]
 [3.         2.44948974 2.        ]]
---------------
1.8257418583505538


**9. Arithematic operations**

In [17]:
x = np.array([(1,2,3),(4,5,6)])
y = np.array([(2,3,4),(5,6,7)])
print(x + y)  # addition
print('-'*20)
print(x-y)    # subtraction
print('-'*20)
print(x*y)    # Multiplication
print('-'*20)
print(y/x)    # Division

[[ 3  5  7]
 [ 9 11 13]]
--------------------
[[-1 -1 -1]
 [-1 -1 -1]]
--------------------
[[ 2  6 12]
 [20 30 42]]
--------------------
[[2.         1.5        1.33333333]
 [1.25       1.2        1.16666667]]


**10. Vertical & Horizontal Stacking :** if you want to concatenate two arrays and not just add them, you can perform it using two ways – vertical stacking and horizontal stacking.

In [18]:
x = np.array([(1,2,3),(4,5,6)])
y = np.array([(7,8,9),(10,11,12)])
print(np.vstack((x,y)))
print('-'*15)
print(np.hstack((x,y)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**11. ravel :** There is one more operation where you can convert one numpy array into a single column.

In [19]:
x = np.array([(2,3,4),(5,6,8)])
print(x.ravel())

[2 3 4 5 6 8]


**12. Sorting :** 
- Sorting means putting elements in a ordered sequence.

- Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

- The NumPy ndarray object has a function called **sort()**, that will sort a specified array.

In [20]:
# Sorting 1-D array
x = np.array([7,5,9,3,6,7])
print('Sorted array :', np.sort(x))
print('Original array :', x)

Sorted array : [3 5 6 7 7 9]
Original array : [7 5 9 3 6 7]


**Note:** This method returns a copy of the array, leaving the original array unchanged.

In [21]:
# Sorting a 2-D array
x = np.array([(5,4,8),(9,3,6)])
print( np.sort(x))
print('-'*15)
print( x)

[[4 5 8]
 [3 6 9]]
---------------
[[5 4 8]
 [9 3 6]]


## NumPy Array Iterating

**Iterating Arrays**
- Iterating means going through elements one by one.
- As we deal with multi-dimensional arrays in numpy, we can do this using basic **'for'** loop of python.
- If we iterate on a 1-D array it will go through each element one by one

In [22]:
# Iterate on the elements on 1-D array
arr = np.array([2,4,5,6,7,8,9])

for x in arr:
    print(x)

2
4
5
6
7
8
9


In [23]:
# Iterate in 2-D array
arr = np.array([(1,2,3),(4,5,6)])

# In a 2-D array it will go through all the rows
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [24]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
# Iterate on each scalar element of the 2-D array:

arr = np.array([(1,2,3),(6,7,8)])  

for x in arr:
    for y in x:
        print(y)

1
2
3
6
7
8


In [25]:
# Iterating 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print('-'*15)

# In a 3-D array it will go through all the 2-D arrays.
for x in arr:
    print(x)
       
print('-'*15)    
#To return the actual values, the scalars, we have to iterate the arrays in each dimension.
arr1 =  np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr1:
    for y in x:
        for z in y:
            print(z)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
---------------
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
---------------
1
2
3
4
5
6
7
8
9
10
11
12


### **Iterating arrays using nditer()**


The function **nditer()** is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration

**Iterating on Each Scalar Element**
- In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [26]:
# Iterate through the following 3-D array:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [27]:
# Iterate through every scalar element of the 2D array skipping 1 element
arr = np.array([(1,3,4),(6,8,9)])

for x in np.nditer(arr[:,::2]):
    print(x)

1
4
6
9


### Enumerated Iteration Using ndenumerate()

- **Enumeration** means mentioning sequence number of somethings one by one.

- Sometimes we require corresponding index of the element while iterating, the **ndenumerate()** method can be used for those usecases.

In [28]:
arr = np.array([(1,2,3),(4,5,6)])

for index,values in np.ndenumerate(arr):
    print(index,values)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


## Random Numbers in NumPy

- Random number does NOT mean a different number every time. Random means something that can not be predicted logically.
- Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.
- If there is a program to generate random number it can be predicted, thus it is not truly random.
- Random numbers generated through a generation algorithm are called **pseudo random**.

### Generate Random Number

NumPy offers the **random** module to work with random numbers.

In [29]:
from numpy import random

In [30]:
# Generate a 2 random integers from 0 to 100:
# low value is inclusive and high value is exclusive, size parameter where you can specify the shape of an array.
x = random.randint(low = 0,high = 100,size =2)
print(x)

[59  0]


In [31]:
# Q. Generate a random float from 0 to 1:
# Answer : The random module's rand() method returns a random float between 0 and 1.

x = random.rand()
print(x)

0.12321322033598558


In [32]:
# Generate a 1-D array containing 5 random floats between 0 to 1.
x = random.rand(5)
print(x)

[0.93955698 0.6147055  0.36375717 0.50443324 0.57969228]


In [33]:
# Generate a 2-D array with 3 rows, each row containing 5 random floats between 0 to 1.
x = random.rand(3,5)
print(x)

[[0.12797799 0.66590167 0.63768217 0.64918426 0.9649663 ]
 [0.54417789 0.94175647 0.30723866 0.62604555 0.93906012]
 [0.97683691 0.86626547 0.88171246 0.14126429 0.21059001]]
